### ISSUE TITLE
Any example of SOAP sign?

### ISSUE THREAD

**Issue by iGrog** [robrichards/xmlseclibs#102]
Digitally sign (detached type XML Digital Signature) the whole SOAP message with the Private Key of Sender Certificate and put the signature into SOAP-header?
Any example to get desired?

**Comment by stamster** [comment]
Check this out.
#69

**Comment by Overtonesinger** [comment]
Example of SOAP sign? Not **yet**!
But it **will** exist soon - because I just **have to** figure it out in my PHP 5.6 project...  I will put it here as soon as I have working example...
(Implementing a client for webservice called "Electronic Registration of Sales"...)

**Comment by robrichards** [comment]
Have you looked at https://github.com/robrichards/wse-php? Even if you don't use the library you can reference it for how to sign SOAP messages.

**Comment by Overtonesinger** [comment]
**WS-security** extension to SOAP? That was exactly what I needed. Thank You a lot! :+1:
