### ISSUE TITLE
Namespaces error

### ISSUE THREAD

**Issue by diegomh** [robrichards/xmlseclibs#105]
Hello team, I have a problem with this library, I can sign a document without namespaces and the signature is correct, but when I add one namespaces the  generated signature is incorrect, this is a example:

With this XML, the signature is correct:

<?xml version="1.0" encoding="UTF-8"?>
<Invoice>
    <to id="test">Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Hola</body>
</Invoice>

With this XML the signature is incorrect:

<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2">
    <to id="test">Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Hola</body>
</Invoice>

This is my code:
$doc = new DOMDocument();
$doc->load('test.xml');
$objDSig = new XMLSecurityDSig();
$objDSig->setCanonicalMethod(XMLSecurityDSig::C14N);
$objDSig->addReference(
    $doc, 
    XMLSecurityDSig::SHA1, 
    array('http://www.w3.org/2000/09/xmldsig#enveloped-signature'),
    array('force_uri' => true)
);
$objKey = new XMLSecurityKey(XMLSecurityKey::RSA_SHA1, array('type'=>'private'));
$objKey->loadKey('privkey.pem', TRUE);
$objDSig->sign($objKey);
$objDSig->add509Cert(file_get_contents('mycert.pem'), true, false, array("force_uri" => true));
$objDSig->appendSignature($doc->documentElement);
$doc->save('test_signed.xml');

Sorry for my english, but I need help, I don´t know  why this problem happens.
Thank you
Regards

**Comment by robrichards** [comment]
Why do you say the signature is incorrect?

**Comment by robrichards** [comment]
Please re-open if this issue persists.
