### ISSUE TITLE
How to sign with PFX

### ISSUE THREAD

**Issue by KhanMaytok** [robrichards/xmlseclibs#106]
Hi, I want to sign an XML with PFX. The example is with pem. How can I do it? I try convert the files with 

openssl pkcs12 -in client_ssl.pfx -out client_ssl.pem -clcerts

openssl pkcs12 -in client_ssl.pfx -out root.pem -cacerts

but when I try to sign, I obtain this error:

    Warning: openssl_sign(): supplied key param cannot be coerced into a private key in C:\xampp\htdocs\facturacion\tests\src\XMLSecurityKey.php on line 468

**Comment by robrichards** [comment]
Take a look in the tests directory at the privkey.pem file. It is quite possible your exported key has additional information that you need to remove from the file in order for it to be loaded properly.

**Comment by robrichards** [comment]
please re-open if you still experience the issue after verifying key format
