### ISSUE TITLE
 Insert signature at a given node

### ISSUE THREAD

**Issue by jcaguilar40** [robrichards/xmlseclibs#116]
Dear, I have the following xml:

`<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:qdt="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2" xmlns:sac="urn:sunat:names:specification:ubl:peru:schema:xsd:SunatAggregateComponents-1" xmlns:udt="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ext:UBLExtensions>
    <ext:UBLExtension>
      <ext:ExtensionContent>
        <sac:AdditionalInformation>
          <sac:AdditionalMonetaryTotal>
            <cbc:ID>1001</cbc:ID>
            <cbc:PayableAmount currencyID="PEN">148.5</cbc:PayableAmount>
          </sac:AdditionalMonetaryTotal>
          <sac:AdditionalProperty>
            <cbc:ID>1000</cbc:ID>
            <cbc:Value>CIENTO  SETENTA Y CINCO CON 2/100</cbc:Value>
          </sac:AdditionalProperty>
          <sac:SUNATTransaction>
            <cbc:ID>01</cbc:ID>
          </sac:SUNATTransaction>
        </sac:AdditionalInformation>
      </ext:ExtensionContent>
    </ext:UBLExtension>
    <ext:UBLExtension>
      <ext:ExtensionContent>`

 the question is How do I get the result of the signature to be inserted into the <ext: ExtensionContent> node ?. (The second tag).

Thanks for your valuable contribution

**Comment by Overtonesinger** [comment]
Please, insert the XML again,  but using the  `"<>"` button ... to insert and let it display  as the raw code. :-)
Thanx.

**Comment by cpjeanpaul** [comment]
```
<root>
<child>hello</child>
<otherchild>
<ds:Signature>...</ds:Signature>
<otherchild>
</root>
```
Something like this?

**Comment by cpjeanpaul** [comment]
`$objDSig->appendSignature($doc->getElementsByTagName("otherchild")->item(0));`

**Comment by langaro** [comment]
@cpjeanpaul thank you so much. 👍 💯
