### ISSUE TITLE
Readdress test extract win cert

### ISSUE THREAD

**Issue by skymeyer** [robrichards/xmlseclibs#118]
The test https://github.com/robrichards/xmlseclibs/blob/master/tests/extract-win-cert.phpt#L46 is expecting `XMLSecurityKey::loadKey` to fail when trying to load from https://github.com/robrichards/xmlseclibs/blob/master/tests/mycert.win.pem.

OpenSSL used to be very picky about the PEM format (see https://goo.gl/nInxXq) and based on the referenced test I'm assuming that this test was purposely build to fail when passing in "incorrectly" (at least from an OpenSSL perspective) PEM encoded certificate. However this now seems to be address in OpenSSL (also see https://rt.openssl.org/Ticket/Display.html?id=3155).

Using OpenSSL 1.0.1k-fips this fails as expected (same behavior in PHP):
```bash
openssl x509 -in tests/mycert.win.pem 
unable to load certificate
139713050662544:error:0906D064:PEM routines:PEM_read_bio:bad base64 decode:pem_lib.c:812:
```

Using OpenSSL 1.0.1t this works now (also in PHP):
```bash
openssl x509 -in tests/mycert.win.pem
-----BEGIN CERTIFICATE-----
MIIEVDCCAzygAwIBAgIJAPTrkMJbCOr1MA0GCSqGSIb3DQEBBQUAMHkxCzAJBgNV
BAYTAlVTMQ4wDAYDVQQIEwVNYWluZTESMBAGA1UEBxMJTGltaW5ndG9uMR8wHQYD
VQQKExZ4bWxzZWNsaWJzLnBocCBMaWJyYXJ5MSUwIwYDVQQDExx4bWxzZWNsaWJz
L3d3dy5jZGF0YXpvbmUub3JnMB4XDTA4MDcwNzIwMjIzMVoXDTE4MDcwNTIwMjIz
MVoweTELMAkGA1UEBhMCVVMxDjAMBgNVBAgTBU1haW5lMRIwEAYDVQQHEwlMaW1p
bmd0b24xHzAdBgNVBAoTFnhtbHNlY2xpYnMucGhwIExpYnJhcnkxJTAjBgNVBAMT
HHhtbHNlY2xpYnMvd3d3LmNkYXRhem9uZS5vcmcwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDttdMyM5ISVD1Uz+BHAPrxVJ6N1eZonfg3DMvZVT0Zy64+
qcXj8zuHC6lolDsfGnD8LUttraQ7qCL+bHKps+hjAhCRdx5Wcn4iDrlFpxFL7INn
r6vekzsCQ45BPUrvksF9FKa7yX4iSDButmPfoT14gPnIuSe8Y5UeGe6Lk6sF0WgH
yL+JmxOu377Kuhah2pXZ1+z7V4JIlNgemJtKlqrvgGeuE9TagfGHUL9BuZK5fUx/
RSDUjqxUeKU3fft9fGIAZl0dduitC2Otv4dr1gxLrUmI+ZZ75FmtfKQT7SmS92QV
I2B5WAPlL1bnbvhkZiyw7nFE+Q/wGJ2myE4RIFjdAgMBAAGjgd4wgdswHQYDVR0O
BBYEFEC5iG0uGXLpQG/zMj/4TuDWfTpHMIGrBgNVHSMEgaMwgaCAFEC5iG0uGXLp
QG/zMj/4TuDWfTpHoX2kezB5MQswCQYDVQQGEwJVUzEOMAwGA1UECBMFTWFpbmUx
EjAQBgNVBAcTCUxpbWluZ3RvbjEfMB0GA1UEChMWeG1sc2VjbGlicy5waHAgTGli
cmFyeTElMCMGA1UEAxMceG1sc2VjbGlicy93d3cuY2RhdGF6b25lLm9yZ4IJAPTr
kMJbCOr1MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBACmSKrte07Vr
GB8dtrN5mrt28ILickQjguu46h6vChgQ4YfIAoA1KWNsZJUuuIzTDjE5xz2hsW37
CI0yrNesv2ho2hhP+fIaxCGmcwLYXL80UaPRglYk5+wPWFOt3QFAVoEgwjLX9+y+
c2Gu7xLgHAFZVRjQ5hhKT0Nj3vhnt0k8LcognNl1wKuWda7VL4tODp/2IOXr5o5v
/OL3UesGfeWfvr8LVmMc5f7/vLAu1+2Yk+/C9/EZyf3BDZQ4z8ae/iwqprCTUIEj
hUDcq4+0YN2EIw6suGE2FtWlsIywNErmoOhdrmntU61n3nFCQBi7QDUnZrAFrl4/
bmk3eRJ00nE=
-----END CERTIFICATE-----
```
Currently it seems that the stacks from Travis are using an older OpenSSL as the above mentioned test still passes. However when running the same unit test suite locally using `php:7.0-cli` docker image, the test assumption no longer passes.

@RichWeber can you elaborate what the actual intent was ? Once the stacks on Travis get updated we will start seeing failures on this one.

**Comment by thijskh** [comment]
I have proposed a PR to drop this test: #133. @RichWeber please let us know if you have anything to add.

**Comment by RichWeber** [comment]
nope
