### ISSUE TITLE
SHA256 Support with PHP 5.3

### ISSUE THREAD

**Issue by ashyam41** [robrichards/xmlseclibs#119]
If we have PHP 5.3 installed on the server, does this library support SHA256 key type?
As per the PHP manual (http://us2.php.net/manual/en/openssl.signature-algos.php), SHA256 is supported only from 5.4.8.
Please confirm.

**Comment by robrichards** [comment]
It still should work. It's just the constants themselves were added in 5.4.8. I used the textual names in the library in order to be able to use the additional algorithms.

**Comment by ashyam41** [comment]
Thanks, we'll give it a shot.
