### ISSUE TITLE
Migration from mcrypt PHP extension to OpenSSL

### ISSUE THREAD

**Issue by RauchF** [robrichards/xmlseclibs#120]
Hello,

as you are probably aware, the mcrypt PHP extension [has been deprecated](https://wiki.php.net/rfc/mcrypt-viking-funeral) as of PHP 7.1.0 and will be removed with PHP 7.2.0.
Since 7.1 is the current latest stable PHP version, I would like to suggest migration to the openssl extension.

As part of this, it probably should be investigated whether the OpenSSL version used in PHP 5.3 supports all used ciphers.

What do you think of this?

**Comment by thijskh** [comment]
This is a duplicate of #55 and #101. I believe your help is welcome there to get that tested and merged.

**Comment by RauchF** [comment]
Oh, sorry. Somehow I overlooked them when I searched for mcrypt. :see_no_evil: 

I'll go over to #101 and participate there :)
