### ISSUE TITLE
openssl_sign(): supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by tarikhagustia** [robrichards/xmlseclibs#121]
im work on PHP 7 and i Got this error
`openssl_sign(): supplied key param cannot be coerced into a private key`

this is my code
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ApplicationArea;
use Carbon\Carbon;
use DB;
use RobRichards\XMLSecLibs\XMLSecurityDSig;
use RobRichards\XMLSecLibs\XMLSecurityKey;
class LatihanController extends Controller
{
    public function index()
    {
      // Load the XML to be signed
      $doc = new \DOMDocument();
      $doc->load('bs.xml');

      // Create a new Security object
      $objDSig = new XMLSecurityDSig();
      // Use the c14n exclusive canonicalization
      $objDSig->setCanonicalMethod(XMLSecurityDSig::EXC_C14N);
      // Sign using SHA-256
      $objDSig->addReference(
          $doc,
          XMLSecurityDSig::SHA1,
          array('http://www.w3.org/2000/09/xmldsig#enveloped-signature')
      );

      // Create a new (private) Security key
      $objKey = new XMLSecurityKey(XMLSecurityKey::RSA_SHA1, array('type'=>'private'));
      $objDSig->sign($objKey);

      // Add the associated public key to the signature
      $objDSig->add509Cert(file_get_contents('./path/to/file/mycert.pem'));

      // Append the signature to the XML
      $objDSig->appendSignature($doc->documentElement);
      // Save the signed XML
      $doc->save('./path/to/signed.xml');

    }
}
`

**Comment by robrichards** [comment]
You never loaded your key. $objKey->loadKey(...)
