### ISSUE TITLE
Prefix "ds" in Signature node.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [robrichards/xmlseclibs#13]
```
I had problems with my signature validations by the prefix "ds", so I made 
changes to indicate whether the firm is required prefix or not.


Attachment changes made.


require(dirname(__FILE__) . '/../xmlseclibs.php');

if (file_exists(dirname(__FILE__) . '/sign-basic-test.xml')) {
    unlink(dirname(__FILE__) . '/sign-basic-test.xml');
}

$doc = new DOMDocument(); 
$doc->formatOutput = FALSE; 
$doc->preserveWhiteSpace = TRUE;

$semilla = getSeed();
$xml = 
"<getToken>\n\t<item>\n\t\t<Semilla>$semilla</Semilla>\n\t</item>\n</getToken>";

$doc->loadXML($xml);
$objDSig = new XMLSecurityDSig(FALSE);
//die;
$objDSig->setCanonicalMethod(XMLSecurityDSig::C14N);
$options['prefix'] = '';
$options['prefix_ns'] = '';
$options['force_uri'] = TRUE;
$options['id_name'] = 'ID';
$objDSig->addReference($doc, XMLSecurityDSig::SHA1, 
array(XMLSecurityDSig::TR_ENV_SIG), $options);

$objKey = new XMLSecurityKey(XMLSecurityKey::RSA_SHA1, 
array('type'=>'private'));
$pfx = file_get_contents(dirname(__FILE__) . "/file.pfx");
openssl_pkcs12_read($pfx, $key, "pass");
$objKey->loadKey($key["pkey"]);
$objDSig->add509Cert($key["cert"]);
$objDSig->sign($objKey, $doc->documentElement);

$doc->save(dirname(__FILE__) . '/sign-basic-test.xml');
```

Original issue reported on code.google.com by `atiruz` on 20 Sep 2012 at 9:35

Attachments:
* [xmlseclibs.php](https://storage.googleapis.com/google-code-attachments/xmlseclibs/issue-13/comment-0/xmlseclibs.php)
* [sign-basic-test.xml](https://storage.googleapis.com/google-code-attachments/xmlseclibs/issue-13/comment-0/sign-basic-test.xml)

**Comment by robrichards** [comment]
The constructor for the XMLSecurityDSig now takes an optional argument for defining the prefix, if any, to be used. When not passed it uses default behavior. When set to an empty string or null, it won't use a prefix, otherwise it will use the prefix passed in. See the xml-sign-prefix.phpt test for an example

**Comment by akshaykmr286** [comment]
Wdf..
Not helpfull..Y do u suggest nonsense..

**Comment by rodrigoferra** [comment]
To remove the prefix you can pass a new prefix as parameter to class.
$objDSig = new XMLSecurityDSig('');

**Comment by langaro** [comment]
@rodrigoferra Thank you!

**Comment by falinhares** [comment]
Thanks @rodrigoferra for the tip. Solved my problem here!
