### ISSUE TITLE
vulnerability in XMLsecLibs 

### ISSUE THREAD

**Issue by attritionorg** [robrichards/xmlseclibs#162]
Per https://simplesamlphp.org/security/201802-01 advisory, appears XMLsecLibs is impacted. They say other vendors were contacted but not if upstream was. Sharing it here in case you were not in the loop.

**Comment by attritionorg** [comment]
ping @robrichards

**Comment by attritionorg** [comment]
Right, but the 'fix' sounds like it was implemented within SimpleSAMLphp, and not in XMLsecLibs itself. That is what I am trying to verify, if any fixes were pushed within XMLsecLibs, or as you say, it requires a significant effort and for now, those using the library should work around it.

**Comment by robrichards** [comment]
The fix was made in SimpleSAMLphp but I am making a release with the change back ported to here as well

**Comment by adityawebi** [comment]
Hi Robrichards, Can you please confirm in which branch this release is available? Since 2.0 branch seems latest but cant see this patch/commit in there.

**Comment by robrichards** [comment]
I will resolve this before end of week. Been hesitant to release as there is a slight possibility of breaking BC and breaking spec compliance which I am trying to avoid.

**Comment by robrichards** [comment]
Final changes pushed with 3.0.2
