### ISSUE TITLE
Potential Vulnerability VU#475445?

### ISSUE THREAD

**Issue by runcoach** [robrichards/xmlseclibs#163]
I was specifically asked about this vulnerability today. xmlseclibs does not appear on the affected or not affected list. Just putting it on the radar https://www.kb.cert.org/vuls/id/475445

**Comment by robrichards** [comment]
@runcoach I don't believe so otherwise OneLogin's php implementation would have been flagged as well and I haven't heard anything regarding the issue

**Comment by robrichards** [comment]
Thanks, Yes there are a couple of more changes that need to go in before I make a release. Will leave this open until then

**Comment by robrichards** [comment]
The finally changes have been pushed in 3.0.2
