### ISSUE TITLE
Add PHP 7.2 to travis.yml

### ISSUE THREAD

**Issue by gfaust-qb** [robrichards/xmlseclibs#167]
Hi,

in PR #165 I wrote about problems of travis with PHP 7 (already fixed by travis) and adding PHP 7.2 to travis.yml. 
The PR tested xmlseclibs already against PHP 7.2 and will pass all the tests, so I suggest to add it before someone adds code that has to be refactored later because it has not been tested against PHP 7.2

Kind Regards

Guido

**Comment by robrichards** [comment]
merged
