### ISSUE TITLE
$doc->isSame($this->sigNode) is always false

### ISSUE THREAD

**Issue by GoogleCodeExporter** [robrichards/xmlseclibs#17]
```
Fix validate references for documents like 
<signature><object>data</object></signature>
```

Original issue reported on code.google.com by `luisalbertolg@gmail.com` on 13 Apr 2013 at 7:51

Attachments:
* [xmlseclibs.php.patch](https://storage.googleapis.com/google-code-attachments/xmlseclibs/issue-17/comment-0/xmlseclibs.php.patch)

**Comment by robrichards** [comment]
I used a different fix for this which has better performance than using XPath.
