### ISSUE TITLE
Updated release?

### ISSUE THREAD

**Issue by akinspe** [robrichards/xmlseclibs#177]
Can we get a release for 3.0.2? There is a downstream project that is relying on the changes since 3.0.1

**Comment by jaimeperez** [comment]
@robrichards this is very much needed. There are security fixes in place that haven't seen the light due to the lack of new stable releases. Could you please tag 93f8c07976b36b6050ab341ab5850484dc897ce0 as 3.0.2?

**Comment by robrichards** [comment]
3.0.2 is finally out

**Comment by jaimeperez** [comment]
Thanks Rob!

Just for your info, we've published three security advisories for the issues fixed here:

https://simplesamlphp.org/security/201809-01
https://simplesamlphp.org/security/201809-02
https://simplesamlphp.org/security/201809-03
