### ISSUE TITLE
PHP Warning: Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' (this will throw an Error in a future version of PHP) in /app/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php on line 136

### ISSUE THREAD

**Issue by seismicmike** [robrichards/xmlseclibs#196]
Hi, I recently ran into the issue from https://github.com/robrichards/xmlseclibs/issues/148 while using 2.1.0 of this library on PHP 7.2.

Specifically:

> PHP Warning: Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' (this will throw an Error in a future version of PHP) in /app/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php on line 136
> PHP Warning: Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC' (this will throw an Error in a future version of PHP) in /app/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php on line 137
> PHP Warning: Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' (this will throw an Error in a future version of PHP) in /app/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php on line 136

Is this an issue that can be resolved by removing usage of Mcrypt? php-mcrypt has been removed from PHP 7.2.

**Comment by tvdijen** [comment]
Upgrade to 3.x and your warnings will magically disappear

**Comment by tvdijen** [comment]
@robrichards I think it's safe to close this one.. The issue was resolved in v3 of the library.
You may want to update the README on master though.. 3.x isn't mentioned there at all

**Comment by robrichards** [comment]
Thanks
