### ISSUE TITLE
Fork with namespaces

### ISSUE THREAD

**Issue by GoogleCodeExporter** [robrichards/xmlseclibs#22]
```
Hello.
Here is fork with namespaces (and 2 bugs fixed):
https://github.com/jamm/XMLSecurity

If owner of original code will request to delete this - I'll delete it.
Hope this code will be useful somehow for somebody.
```

Original issue reported on code.google.com by `normandi...@gmail.com` on 3 Sep 2013 at 12:48

**Comment by Dashron** [comment]
Any interest in a PR adding namespaces? I need to add them for a project.

**Comment by robrichards** [comment]
@Dashron There is. My plan was to use master as the 2.x version supporting namespaces. I haven't had the time to finish it but was working on taking the code from the 1.4 branch and using that to create the namespace version so I have a working master again. If you happen to have it already done I would gladly accept a PR for it

**Comment by Dashron** [comment]
Any preference on keeping classes in the same file, or splitting them out and supporting PS4 autoloading?

**Comment by robrichards** [comment]
@Dashron Split them into their own files so it can support PSR-4. Thats why you should start with the 1.4 branch as it already has them split out for autoload support but is mean to be run under PHP 5.2 which is why the namespace support will be for the 2.x version only.

**Comment by Dashron** [comment]
Ahhh I see now. So I'll submit a PR that...

Adds namespaces to the 1.4 branch.
Merged the 1.4 branch with namespaces into master.
Passes all tests (still working on getting php's test system running, I'm more used to phpunit)

**Comment by robrichards** [comment]
actually leave the 1.4 as is. just use that as the base for master and add the namespaces there. 1.4 needs to stay as it is. I will be back porting any changes from master to 1.4 so I can keep the PHP 5.2 support in the 1.4 branch.

**Comment by robrichards** [comment]
@Dashron ^^

**Comment by Dashron** [comment]
Cool, I won't break your 1.4 branch. Got the tests running, just cleaning it up now.

**Comment by Dashron** [comment]
https://github.com/robrichards/xmlseclibs/pull/54 

I'm still incorporating it into our production environment, and will let you know when that's finalized and tested. Let me know if you have any observations in the meanwhile.

**Comment by Dashron** [comment]
Runs great in production. Let me know if you need anything!

**Comment by robrichards** [comment]
@Dashron Thanks. I'll start reviewing it tomorrow.

**Comment by robrichards** [comment]
now part of the 2.x version
