### ISSUE TITLE
Use of RSA Algorithm without OAEP

### ISSUE THREAD

**Issue by infocube-dev-team** [robrichards/xmlseclibs#260]
A scan we have executed on the source code of the library (version 3.1.0, latest at time of writing) highlighted that the encryption function at RSA/ECB/PKCS1Padding is using a weak padding scheme.

With RSA encryption, ensure that the padding scheme used is OAEP. While PKCSv1 may be default for several libraries, frameworks, or languages, it is known to be weak and should not be used.

The affected file is xmlseclibs-3.1.0/src/XMLSecurityKey.php at lines 486, 501, 516, 531.

Please let us know if this is a genuine issue or a false positive.

**Comment by tvdijen** [comment]
The padding scheme depends on the encryption algorithm being used:
https://github.com/robrichards/xmlseclibs/blob/3.1.1/src/XMLSecurityKey.php#L185-L207

Unless you're using RSA 1.5, the padding scheme is set to OAEP.

**Comment by infocube-dev-team** [comment]
Thank you, it is clear.

PS
When I open https://github.com/robrichards/xmlseclibs I see that the release marked as "latest" is 3.1.0.
I will upgrade to 3.1.1.

Thanks for the support!
