### ISSUE TITLE
Class 'XMLSecurityDSig' not found

### ISSUE THREAD

**Issue by vesvello** [robrichards/xmlseclibs#61]
Im newbie

Any help with this?

Thanks in advance

**Comment by robrichards** [comment]
You should refer to the code in the tests directory such as the basic signature:
https://github.com/robrichards/xmlseclibs/blob/master/tests/xml-sign.phpt

**Comment by Maks3w** [comment]
This is because the example present on README.md is outdated about the namespaces and file split
