### ISSUE TITLE
incorrect <DigestValue> comparison result when the document has whitespace in the value (e.g. with a SHA-512 digest which is line-breaked after 76 characters)

### ISSUE THREAD

**Issue by restena-sw** [robrichards/xmlseclibs#62]
According to XMLDSIG, the <DigestValue> element is a base64Binary type, which is allowed to contain embedded whitespace.

Your function calculateDigest() uses base64_encode() which produces a whitespace-free base64 representation of the selected digest’s value.

The document itself may contain a base64 representation of the same value which has whitespace for its own reasons (e.g. if the base64 representation of the digest is longer than 76 characters (such as is the case with SHA-512), it may have added a line break which was converted by the XML parser to a single inline whitespace character before passing it on for validation).

The comparison in function validateDigest(), around line 298:
return ($digValue == $digestValue);

will fail if the base64-encoded representations of the same actual digest value differ in whitespace only; while it should not fail.

The obvious one-line fix to this is
return (base64_decode($digValue) == base64_decode($digestValue));

but a more thorough way of fixing might be to let calculateDigest() return a direct binary value, and only let the calling functions encode this with base64_encode() if they have a need for it.

NB: your code is already doing this correctly/consistently in other places, such as when comparing the <SignatureValue> element, in function verify() around line 662:

return $objKey->verifySignature($this->signedInfo, base64_decode($sigValue));

Here you are correctly getting rid of whitespace if any, by comparing the binary representations, not the base64 encoded versions.

**Comment by robrichards** [comment]
@restena-sw Do you have a reference document I can use to work with?

**Comment by restena-sw** [comment]
Sure:

http://registry.eduid.lu/metadata/upstream.xml

this document gets validated by a different validator (based on the
Shibboleth software, as much as I know) just fine; see

https://validator.edugain.org/?edugain=LU (after the validation
finishes, go to the "Signing Info" tab)

Greetings,

Stefan Winter

**Comment by robrichards** [comment]
@restena-sw Did you test with that change? Even comparing the binary values I am coming up with a different value. If you have a test working against that document can you please send me the test code you are using?

**Comment by restena-sw** [comment]
Hi,

> @restena-sw <https://github.com/restena-sw> Did you test with that
> change? Even comparing the binary values I am coming up with a
> different value. If you have a test working against that document can
> you please send me the test code you are using?
>

I didn't up until now; but with time to kill on a train I crafted a
testcase and added some echo to see what's happening:

(this is dumping $digValue and $digestValue, once literally, once with
base64_decode() )

***
HEgAwROJOpIcTMqyta7VkKKbt8fqBrZV4RbvnJcCn8NXEiB8ygqX+rfQTqwOOhNHJrUFfWoywFIEe+V30zVaug==
***
<-->
*** HEgAwROJOpIcTMqyta7VkKKbt8fqBrZV4RbvnJcCn8NXEiB8ygqX+rfQTqwOOhNH
JrUFfWoywFIEe+V30zVaug== ***

(values differ in the extra line feed)

*** H??:?Lʲ??Ր??????U???W |?
????N?:G&?}j2?R{?w?5Z? ***
<-->
*** H??:?Lʲ??Ր??????U???W |?
????N?:G&?}j2?R{?w?5Z? ***

(from what the lousy terminal output allows to see, the binary value
seems the same)

So this does work here - I am testing against the 1.3.1 version of
xmlseclibs which ships with simplesamlphp-1.13.2.

The magic is of course to simply add those lines before the "return" of
validateDigest():

        echo "*** $digValue ***
<-->
*** $digestValue ***
";
        echo "*** ".base64_decode($digValue)." ***
<-->
*** ".base64_decode($digestValue)." ***";

This would allow to see for yourself what's going on.

I will confirm this on an actual installation of SSP, I did this on my
Mac laptop.

**Comment by robrichards** [comment]
@restena-sw If you can, can you put everything including the XML file in a tarball and send it to me? For some reason I am generating a completely different digest so somehow the XML file I am using isn't the raw file - and I've even tried loading it into the DOM directly.

Here is the test code I am trying with:
```
$doc = new DOMDocument();

$doc->load(dirname(__FILE__) . "/upstream.xml");
//$doc->load('http://registry.eduid.lu/metadata/upstream.xml');
$objXMLSecDSig = new XMLSecurityDSig();
	
$objDSig = $objXMLSecDSig->locateSignature($doc);
if (! $objDSig) {
	throw new Exception("Cannot locate Signature Node");
}
$objXMLSecDSig->canonicalizeSignedInfo();
	
try {
	$retVal = $objXMLSecDSig->validateReference();
} catch (Exception $e) {
	echo "Reference Validation Failed\n";
	exit;
}

echo "Reference Validation Success\n";
```

Testing with the 1.3 and 1.4 branches I am generating a digest of:
z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==

**Comment by restena-sw** [comment]
With your code, I also get a different value, both for base64 and
binary. That is mighty strange. My testcase code does largely the same
thing.

It uses fopen and fread to load the file, but from then does by and
large the same things). It also uses a custom XPath query function to
locate the Signature, which is borrowed code from simpleSAMLphp. None of
this should make a difference though.

Can you let me know your mail address - I don't think GitHub allows for
upload of a tar file. Mine is stefan dot winter at restena dot lu.

Stefan

**Comment by restena-sw** [comment]
Ah, got it: the difference in my testcase is that I set the ID node:

$objXMLSecDSig = new XMLSecurityDSig();
$objXMLSecDSig->idKeys[] = 'ID';

That second line triggers the change - if it is not there, I get the
same hash that you have.

Stefan

**Comment by robrichards** [comment]
@restena-sw Completely missed that and I was even looking at the referenced attribute. Fixed now

Thanks!

Rob

**Comment by restena-sw** [comment]
Hi,

one quick question... was that commit for 2.0.0-dev, 1.4, 1.3, or all of
those (I don't know GitHub very well). I'm asking because I need this
functionality in the next simpleSAMLphp, and wonder which version of
xmlseclibs has the fix, so would be suitable for inclusion in SSP...

Greetings,

Stefan Winter

**Comment by robrichards** [comment]
@restena-sw It is in the 2.0 and 1.4 branches. I have depreciated the 1.3 branch to security and critical fixes only. 1.4 is a drop in replacement btw. even tho i've broken the classes out I am maintaining the xmlseclibs file for people needing to upgrade and don't have time to change to use composer or autoloading

**Comment by jaimeperez** [comment]
Thanks a lot for fixing this @robrichards!

I'm certainly willing to bump the version of the library we are using in SSP. Since master is probably not stable enough yet, I guess we'll continue to depend on 1.4. But then I would need a new release to point to, probably 1.4.1. Do you see any problem on releasing a new version that we can use as a minimum requirement?

**Comment by robrichards** [comment]
@jaimeperez Any preference? Master is stable as it and 1.4 are in sync functionally right now. The only difference between it and 1.4 branch is that Master requires 5.3+ rather than 5.2+ and also will cause you to modify code as it uses true namespaces. 1.4 is a BC drop-in for 1.3. I had just been holding off on release the 2.0 version as I was trying to see how many of the bug reports I could get through first but if you rather use the 2.x branch I have no problems cutting a release.

**Comment by jaimeperez** [comment]
Uhm, I guess both options are not exclusive. Using a 1.4.1 has the advantage that we can update immediately and that way solve the issue that Stefan is having with SHA512 signatures.

On the other hand, I don't mind moving to xmlseclibs 2.0 after making sure everything works correctly. In the end, the biggest changes are related to the split into classes, adding namespaces and so on, so I don't expect any issues with core functionality. I would need to update my code to make use of the new classes, of course, but that shouldn't be a big issue.

So I would say: at least a 1.4.1, and if you feel comfortable with master enough to release 2.0, then go for it too, and I'll start migrating our code in SimpleSAMLphp.

**Comment by robrichards** [comment]
@jaimeperez both 2.0.0 and 1.4.1 are available so pick which you like

**Comment by jaimeperez** [comment]
Great, thanks @robrichards!
