### ISSUE TITLE
Some Typos in XMLSecurityKey

### ISSUE THREAD

**Issue by gfaust-qb** [robrichards/xmlseclibs#63]
I fixed some typos in XMLSecurityKey. 
For downwards compability I signed the method getAlgorith() as deprecated and added the new method getAlgorithm(). To avoid duplicate code I moved it from getAlgorith() to getAlgorithm() and replaced the implementation of getAlgorith() with the call of getAlgorithm().

**Comment by robrichards** [comment]
pushed with the docs
