### ISSUE TITLE
Adding (autogenerated) PHPdoc-Blocks

### ISSUE THREAD

**Issue by gfaust-qb** [robrichards/xmlseclibs#65]
Even if there is no need of doc-blocks while using IDEs it is helpfull if you are looking at the code e.g. via Github.

**Comment by Maks3w** [comment]
This is wrong and make a false sense of to be good.

Blocks like you added

```
/** @var null */
$foo = null;
```

Just sucks

**Comment by gfaust-qb** [comment]
Like written in my comment to the PR - it was too late at night ;)

You are right - I agree - nothing more to say ;)
