### ISSUE TITLE
Praise for xmlseclibs (or working with Oracle OSB)

### ISSUE THREAD

**Issue by stamster** [robrichards/xmlseclibs#69]
I'm not sure whenever this is the right place, but I'd like to say thanks for such a great lib for PHP!

As many of other users, I also had a 'chance' to work with gov (i.e. Oracle's) services. This lib helped me a lot to understand the inner workings of xml-dsig, canonicalization etc. 
So, if someone out there will ever have a chance to work with Oracle OSB interface, I'd like to point some steps in order to avoid pitfalls.
First, do not try to sign the entire message (SOAP envelope), you just need to sign the 'business part' of the message, i.e. `xml<Transaction>..........</Transaction>`  without `xml<soap-env ....> </soap-env>` elements.

The hardest part was to find out how the damn thing (OSB) works with SOAP messages and what happens before it validates signature.
So, you sign your message without any SOAP tags, and then just before sending HTTP POST request with XML-SOAP as body you put back entire SOAP header, SOAP body etc. elements. OSB will wipe them out anyway and send only the business message to validation, but you're required to send entire SOAP elements in order to be able to pass OSB's parser, ugly I know.
And the most interesting part - you just cannot have XML declaration at all! If you leave XML declaration on top of SOAP enveloped message, OSB will not be able to parse the message. So just remove XML delcaration.

Full example:

``` xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope"><soapenv:Header/><soapenv:Body>
<ExampleTransaction>
.... business data ..............
</ExampleTransaction>
</soapenv:Body></soapenv:Envelope>
```

Where only this part:

``` xml
<ExampleTransaction>
.... business data ..............
</ExampleTransaction>
```

is being signed!

Also, you can have any prefix as ds:Signature, it just doesn't care about what you will put there, so I prefer  an empty prefixes, and doing that with xmlseclibs is as easy as: 

``` php
$objDSig = new XMLSecurityDSig(0); //empty string or 0 (which evaluates as an empty value)
```

If anybody have any issues with OSB's black boxes, feel free to post a comment, so we could try to find workaround with joined forces!

**Comment by Overtonesinger** [comment]
**Thanx for the info** @stamster !
I have **stripped XML declaration** from the SOAP-message before sending it like this:
// by extending the private method of SoapClient class in PHP5.6 ...
```
	function __doRequest($request, $location, $action, $version, $one_way = 0) {
		$request = str_replace('<?xml version="1.0" encoding="UTF-8"?>' . "\n" , '', $request);

		$ret = parent::__doRequest($request, $location, $action, $version, $one_way);
		$this->__last_request = $request;
		return $ret;
	}

```
And I have made some good progress!
I will also use your tips for signing the "SOAP payload" only.
