### ISSUE TITLE
Patch: Array to string conversion in src/XMLSecurityDSig.php:852 (v2.0.0)

### ISSUE THREAD

**Issue by andreas-stangl** [robrichards/xmlseclibs#80]
My Certificate "subject" has two "OU" values, therefore I get an "Array to string converstion" error in src/XMLSecurityDSig.php:852.

Here's a patch that fixes my issue:

    diff --git a/src/XMLSecurityDSig.php b/src/XMLSecurityDSig.php
    index 7c67a91..a1cbcd6 100644
    --- a/src/XMLSecurityDSig.php
    +++ b/src/XMLSecurityDSig.php
    @@ -849,7 +849,13 @@ class XMLSecurityDSig
                             if (is_array($certData['subject'])) {
                                 $parts = array();
                                 foreach ($certData['subject'] AS $key => $value) {
    -                                array_unshift($parts, "$key=$value");
    +                                if (is_array($value)) {
    +                                    foreach ($value as $valueElement) {
    +                                        array_unshift($parts, "$key=$valueElement");
    +                                    }
    +                                } else {
    +                                    array_unshift($parts, "$key=$value");
    +                                }
                                 }
                                 $subjectNameValue = implode(',', $parts);
                             } else {

Edit: Just created https://github.com/robrichards/xmlseclibs/pull/81

**Comment by robrichards** [comment]
Closed with https://github.com/robrichards/xmlseclibs/pull/81
