### ISSUE TITLE
HHVM signing node with ID attribute w/out namespace regenerates ID value

### ISSUE THREAD

**Issue by tmilos** [robrichards/xmlseclibs#88]
Have detected this issue when tested [lightSAML/lightSAML](https://github.com/lightsaml/lightsaml) on HHVM on travis-ci. It regenerates signed node ID during ``addReferenceList()`` execution, in case when it does not have a namespace prefix and overwrites it, though it has ID value and overwrite option is false.

It appears it's about different behavior of PHP and HHVM implementation of ``\DOMElement::getAttributeNS()``. XMLSecurityDSig does ~line 632 ``$uri = $node->getAttributeNS($prefix_ns, $id_name);`` regardless if ``$prefix_ns`` is null or not, and PHP returns non-prefixed ID value, while HHVM does not and returns null. 

Solution would be to use ``getAttributeNS()`` or ``getAttribute()`` depending on ``$prefix_ns`` value.

**Comment by robrichards** [comment]
Thanks for the patch

**Comment by tmilos** [comment]
Thanks
