### ISSUE TITLE
Case sensitive in Reference Identifier

### ISSUE THREAD

**Issue by zogs** [robrichards/xmlseclibs#91]
I found a usecase that fails.
I have a XML node with a uppercase ID 
```<Assertion ID="_01846d73-964e-4817-b8b4-ab762bcba4c8" IssueInstant="2015-11-20T14:19:42.715Z" Version="2.0" xmlns="urn:oasis:names:tc:SAML:2.0:assertion">```

The Reference validation method processRefNode() is looking at line 417 to a lower case Id
``` $iDlist = '@Id="'.$identifier.'"';```

This causes the validation to fail...
I don't know if it's possible to care about this particular usecase, i don't know XPath well enougth ^^

Thx for your work !

**Comment by robrichards** [comment]
You need to define the name of the XML id in use when not using the default name. i.e.:

$objXMLSecDSig = new XMLSecurityDSig();
$objXMLSecDSig->idKeys = array('ID');

where idKeys is an array of attribute names you use for ID attributes.
