### ISSUE TITLE
openssl_random_pseudo_bytes is insecure

### ISSUE THREAD

**Issue by relaxnow** [robrichards/xmlseclibs#97]
It appears that openssl_random_pseudo_bytes is, in a large number of configurations, not safe for cryptographic use: https://github.com/paragonie/random_compat/issues/96 .

It might be better to switch to a PHP7 polyfill: https://github.com/paragonie/random_compat

**Comment by willemstuursma** [comment]
@robrichards I'm willing to pick this up, if you'll merge the changes and release a new version. Got some time for this from my employer. Let me know what'd you think.

**Comment by robrichards** [comment]
Dupe of #100
