### ISSUE TITLE
How can i use "insertBefore"

### ISSUE THREAD

**Issue by LibreTitan** [robrichards/xmlseclibs#99]
I can´t do it by this way:  

> $objDSig->appendSignature($doc->documentElement, $doc->getElementsByTagName('ExtensionContent')->item(0));

`<ext:UBLExtensions>
        <ext:UBLExtension>
            <ext:ExtensionContent>
                <sac:AdditionalInformation>
                    <sac:AdditionalMonetaryTotal>
                        <cbc:ID>1001</cbc:ID>
                        <cbc:PayableAmount currencyID="PEN">348199.15</cbc:PayableAmount>
                    </sac:AdditionalMonetaryTotal>
                    <sac:AdditionalMonetaryTotal>
                        <cbc:ID>1003</cbc:ID>
                        <cbc:PayableAmount currencyID="PEN">12350.00</cbc:PayableAmount>
                    </sac:AdditionalMonetaryTotal>
                    <sac:AdditionalMonetaryTotal>
                        <cbc:ID>1004</cbc:ID>
                        <cbc:PayableAmount currencyID="PEN">30.00</cbc:PayableAmount>
                    </sac:AdditionalMonetaryTotal>
                    <sac:AdditionalMonetaryTotal>
                        <cbc:ID>2005</cbc:ID>
                        <cbc:PayableAmount currencyID="PEN">59230.51</cbc:PayableAmount>
                    </sac:AdditionalMonetaryTotal>
                    <sac:AdditionalProperty>
                        <cbc:ID>1000</cbc:ID>
                        <cbc:Value>CUATROCIENTOS VEINTITRES MIL DOSCIENTOS VEINTICINCO Y 00/100</cbc:Value>
                    </sac:AdditionalProperty>
                </sac:AdditionalInformation>
            </ext:ExtensionContent>
        </ext:UBLExtension>
        <ext:UBLExtension>
**            <ext:ExtensionContent>
            </ext:ExtensionContent>**
        </ext:UBLExtension>
    </ext:UBLExtensions>`

**Comment by jcaguilar40** [comment]
Did you solve the problem, my friend?

**Comment by robrichards** [comment]
Closing as no further follow ups. Please re-open if this is still an issue.
